Repository eclipse-edc/FederatedCatalog, pull requests merged in 2022-12, with the labels that each got.

#19 feat(build): add workflow_dispatch event trigger
  .github/workflows/verify.yaml
  core/federated-catalog/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java
  core/federated-catalog/src/test/java/org/eclipse/edc/catalog/query/BatchedRequestFetcherTest.java
  core/federated-catalog/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
  system-tests/end2end-test/e2e-junit-runner/build.gradle.kts
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
Labels: build

#22 feat(workflows): add discord webhook for issues, discussions and pull requests
  .github/workflows/discord-webhook.yml
Labels: no-changelog

#34 docs: prepare publishing to OpenApi
  .github/workflows/apidoc.yaml
  core/federated-catalog/build.gradle.kts
  resources/openapi/yaml/management-api/federated-catalog-api.yaml
  resources/openapi/yaml/management-api/federated-catalog.yaml
Labels: documentation
