Repository eclipse-edc/FederatedCatalog, pull requests merged in 2023-05, with the labels that each got.

#100 fix: compilation
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
Labels: bug

#101 feat: store catalogs instead of offers
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/BatchedRequestFetcher.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/CacheQueryAdapterImpl.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/CacheQueryAdapterRegistryImpl.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/IdsMultipartNodeQueryAdapter.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/store/InMemoryFederatedCacheStore.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/ExecutionManagerTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtensionTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/crawler/CatalogCrawlerTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/query/InMemoryFccQueryAdapterRegistryTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/query/QueryEngineImplTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedRequestFetcherTest.java
  core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApi.java
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiController.java
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CacheQueryAdapter.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CacheQueryAdapterRegistry.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CachedAsset.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CatalogConstants.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/FederatedCacheStore.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/QueryResponse.java
  spi/federated-catalog-spi/src/test/java/org/eclipse/edc/catalog/spi/CachedAssetTest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/ManagementApiClient.java
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java
Labels: bug

#103 fix: Rename callbackAddress to counterPartyAddress
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/IdsMultipartNodeQueryAdapter.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedRequestFetcherTest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/matchers/CatalogRequestMatcher.java
Labels: bug

#104 feat(protocol): add query adapter for the new DSP
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/BatchedRequestFetcher.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/DspNodeQueryAdapter.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/IdsMultipartNodeQueryAdapter.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedRequestFetcherTest.java
  core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
Labels: enhancement, refactoring

#112 build: add action to bump the snapshot version
  .github/actions/bump-version/action.yml
  .github/workflows/release-fcc.yml
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java
Labels: build

#113 chore: update snapshot version to 0.1.0-SNAPSHOT
  .github/actions/bump-version/action.yml
  core/federated-catalog-core/build.gradle.kts
  docs/legal/generateThirdPartyReport.sh
  gradle.properties
  gradle/libs.versions.toml
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java
Labels: build

#114 fix: Use EDC namespace for originator property
  extensions/store/fcc-node-directory-cosmos/src/main/java/org/eclipse/edc/catalog/node/directory/azure/CosmosFederatedCacheNodeDirectoryExtension.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CatalogConstants.java
Labels: bug
