Repository eclipse-edc/FederatedCatalog, pull requests merged in 2024-08, with the labels that each got.

#234 fix: make /catalog/query handle null input
  DEPENDENCIES
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiController.java
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
Labels: bug

#235 docs: publish openapi spec under the catalog-api group
  DEPENDENCIES
  core/crawler-core/build.gradle.kts
  core/federated-catalog-core/build.gradle.kts
  docs/developer/architecture/federated-catalog-apis.md
  extensions/api/federated-catalog-api/build.gradle.kts
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiExtension.java
  extensions/api/federated-catalog-api/src/main/resources/catalog-version.json
  resources/openapi/README.md
  resources/openapi/catalog-api.version
Labels: documentation

#238 refactor: separate sql stores from datasources
  extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheExtension.java
  extensions/store/sql/federated-catalog-cache-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheExtensionTest.java
Labels: refactoring

#241 feat: SQL implementation of `TargetNodeDirectory`
  DEPENDENCIES
  core/federated-catalog-core/build.gradle.kts
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/directory/InMemoryNodeDirectory.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/directory/InMemoryNodeDirectoryTest.java
  extensions/store/sql/target-node-directory-sql/build.gradle.kts
  extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/BaseSqlDialectStatements.java
  extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlTargetNodeDirectory.java
  extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlTargetNodeDirectoryExtension.java
  extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/TargetNodeStatements.java
  extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/schema/postgres/PostgresDialectStatements.java
  extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/schema/postgres/TargetNodeMapping.java
  extensions/store/sql/target-node-directory-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/store/sql/target-node-directory-sql/src/main/resources/target-node-directory-schema.sql
  extensions/store/sql/target-node-directory-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlTargetNodeDirectoryExtensionTest.java
  extensions/store/sql/target-node-directory-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlTargetNodeDirectoryTest.java
  settings.gradle.kts
  spi/crawler-spi/build.gradle.kts
  spi/crawler-spi/src/testFixtures/java/org/eclipse/edc/catalog/spi/testfixtures/TargetNodeDirectoryTestBase.java
Labels: enhancement, persistence

#244 build(deps): bump gradle wrapper to 8.10
  .github/workflows/verify.yaml
  DEPENDENCIES
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: build, dependencies
