Repository eclipse-edc/FederatedCatalog, pull requests merged in 2024-06, with the labels that each got.

#195 fix: use constant as API context
  .github/workflows/verify.yaml
  DEPENDENCIES
  extensions/api/federated-catalog-api/build.gradle.kts
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogCacheQueryApiExtension.java
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
  gradle/libs.versions.toml
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/FccApiContexts.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
  system-tests/end2end-test/connector-runtime/build.gradle.kts
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/CatalogApiClient.java
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
Labels: bug, breaking-change

#196 fix: adopt new test runtime model
  DEPENDENCIES
  gradle/libs.versions.toml
  launchers/build.gradle.kts
  system-tests/component-tests/build.gradle.kts
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/instrumentation/MockInjectionExtension.java
  system-tests/end2end-test/catalog-runtime/build.gradle.kts
  system-tests/end2end-test/connector-runtime/src/main/java/org/eclipse/edc/federatedcatalog/end2end/DataplaneInstanceRegistrationExtension.java
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
Labels: enhancement

#198 chore(test): adopt EDC test runtime model
  DEPENDENCIES
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
  extensions/api/federated-catalog-api/build.gradle.kts
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
  gradle/libs.versions.toml
  system-tests/end2end-test/connector-runtime/src/main/java/org/eclipse/edc/federatedcatalog/end2end/DataplaneInstanceRegistrationExtension.java
Labels: enhancement

#199 refactor: simplify catalog query API
  DEPENDENCIES
  core/federated-catalog-core/build.gradle.kts
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogDefaultServicesExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/CacheQueryAdapterImpl.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/CacheQueryAdapterRegistryImpl.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/QueryEngineImpl.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/QueryServiceImpl.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/store/InMemoryFederatedCatalogCache.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtensionTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/query/InMemoryFccQueryAdapterRegistryTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/query/QueryEngineImplTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/query/QueryServiceImplTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCatalogCacheTest.java
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApi.java
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiController.java
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogCacheQueryApiExtension.java
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
  gradle/libs.versions.toml
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CacheQueryAdapter.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CacheQueryAdapterRegistry.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/FederatedCatalogCache.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/QueryService.java
Labels: enhancement, refactoring, breaking-change

#200 docs: add and improve documentation
  README.md
  docs/developer/architecture/federated-catalog-apis.md
  docs/developer/architecture/federated-catalog.architecture.md
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApi.java
  spi/crawler-spi/src/main/java/org/eclipse/edc/crawler/spi/model/ExecutionPlan.java
  spi/federated-catalog-spi/README.md
Labels: documentation, enhancement

#202 chore: improve some logging
  DEPENDENCIES
  core/crawler-core/src/main/java/org/eclipse/edc/catalog/cache/ExecutionManager.java
  core/crawler-core/src/test/java/org/eclipse/edc/catalog/cache/ExecutionManagerTest.java
Labels: enhancement

#203 feat(build): add multiple launchers
  .github/workflows/verify.yaml
  DEPENDENCIES
  gradle/libs.versions.toml
  launchers/catalog-base/build.gradle.kts
  launchers/catalog-dcp/Dockerfile
  launchers/catalog-dcp/build.gradle.kts
  launchers/catalog-mocked/Dockerfile
  launchers/catalog-mocked/build.gradle.kts
  settings.gradle.kts
Labels: enhancement, build

#208 feat: implements versioning for FederatedCatalogApi
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApi.java
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiController.java
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiExtension.java
  extensions/api/federated-catalog-api/src/main/resources/version.json
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
  resources/openapi/yaml/management-api/federated-catalog-api.yaml
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/CatalogApiClient.java
Labels: enhancement, breaking-change

#210 chore(ci): remove OpenAPI publish job
  .github/workflows/apidoc.yaml
  .github/workflows/release-fcc.yml
Labels: enhancement, build

#211 fix(test): data services are now never null
  DEPENDENCIES
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformerTest.java
Labels: bug
