Repository eclipse-edc/FederatedCatalog, pull requests merged in 2024-02, with the labels that each got.

#163 fix: use correct DataAddress type (src) in E2E test
  DEPENDENCIES
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java
Labels: bug

#164 fix: add missing mapping of `counterPartyId` in `CatalogRequestMessage`
  core/crawler-core/src/main/java/org/eclipse/edc/catalog/cache/ExecutionManager.java
  core/crawler-core/src/main/java/org/eclipse/edc/catalog/cache/crawler/Crawler.java
  core/crawler-core/src/test/java/org/eclipse/edc/catalog/cache/crawler/CrawlerTest.java
  core/crawler-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/BatchedCatalogRequestFetcher.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/DspCatalogRequestAction.java
  core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
  spi/crawler-spi/src/main/java/org/eclipse/edc/crawler/spi/TargetNode.java
  spi/crawler-spi/src/main/java/org/eclipse/edc/crawler/spi/WorkItem.java
  spi/crawler-spi/src/main/java/org/eclipse/edc/crawler/spi/model/UpdateRequest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/matchers/CatalogRequestMatcher.java
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
Labels: bug

#167 chore: incorporate latest changes of EDC
  DEPENDENCIES
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogDefaultServicesExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/store/InMemoryFederatedCacheStore.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
Labels: bug, breaking-change

#168 chore: adapt code to latest EDC
  DEPENDENCIES
  core/crawler-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
  core/federated-catalog-core/build.gradle.kts
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/BatchedCatalogRequestFetcher.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformer.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDataServiceTransformer.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDatasetTransformer.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDistributionTransformer.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedCatalogRequestFetcherTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformerTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToDataServiceTransformerTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToDatasetTransformerTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToDistributionTransformerTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/TestInput.java
  core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
  extensions/api/federated-catalog-api/build.gradle.kts
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
  gradle/libs.versions.toml
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
  system-tests/end2end-test/e2e-junit-runner/build.gradle.kts
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
Labels: bug

#169 docs: fix catalog swagger API
  DEPENDENCIES
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApi.java
Labels: documentation
