Repository eclipse-edc/FederatedCatalog, pull requests merged in 2024-03, with the labels that each got.

#170 docs: publish openapi ui
  .github/workflows/publish-openapi-ui.yml
  .github/workflows/release-fcc.yml
  DEPENDENCIES
Labels: documentation

#172 fix: update import for transformer
  DEPENDENCIES
  core/federated-catalog-core/build.gradle.kts
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformer.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtensionTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedCatalogRequestFetcherTest.java
  extensions/api/federated-catalog-api/build.gradle.kts
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
Labels: bug

#174 fix: move settings into extensions
  DEPENDENCIES
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogDefaultServicesExtension.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CacheSettings.java
Labels: bug

#176 chore: recent EDC updates
  DEPENDENCIES
  extensions/api/federated-catalog-api/build.gradle.kts
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
  system-tests/component-tests/build.gradle.kts
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
  system-tests/end2end-test/e2e-junit-runner/build.gradle.kts
Labels: build

#178 fix: compilation
  DEPENDENCIES
  build.gradle.kts
  core/federated-catalog-core/build.gradle.kts
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogDefaultServicesExtension.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java
  extensions/api/federated-catalog-api/build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  system-tests/component-tests/build.gradle.kts
  system-tests/end2end-test/e2e-junit-runner/build.gradle.kts
Labels: build

#180 chore(compile): fix compile errors after EDC refactor
  DEPENDENCIES
  build.gradle.kts
  core/crawler-core/build.gradle.kts
  core/crawler-core/src/main/java/org/eclipse/edc/catalog/cache/crawler/Crawler.java
  core/crawler-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
  core/federated-catalog-core/build.gradle.kts
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/BatchedCatalogRequestFetcher.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/CacheQueryAdapterImpl.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/CacheQueryAdapterRegistryImpl.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/DspCatalogRequestAction.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/store/InMemoryFederatedCacheStore.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformer.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDataServiceTransformer.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDatasetTransformer.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDistributionTransformer.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtensionTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/query/InMemoryFccQueryAdapterRegistryTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/query/QueryEngineImplTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedCatalogRequestFetcherTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformerTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToDatasetTransformerTest.java
  core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
  extensions/api/federated-catalog-api/build.gradle.kts
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApi.java
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
  gradle/libs.versions.toml
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CacheQueryAdapter.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CacheQueryAdapterRegistry.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CatalogConstants.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/FederatedCacheStore.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/QueryEngine.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/QueryResponse.java
  spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/model/CatalogUpdateResponse.java
  system-tests/component-tests/build.gradle.kts
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/matchers/CatalogRequestMatcher.java
  system-tests/end2end-test/e2e-junit-runner/build.gradle.kts
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/ManagementApiClient.java
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java
Labels: enhancement, breaking-change
