Repository eclipse-edc/FederatedCatalog, pull requests merged in 2024-09, with the labels that each got.

#245 build: fix compilation
  DEPENDENCIES
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDataServiceTransformer.java
Labels: build

#247 ci: fix tests on main by removing unneeded dependency
  DEPENDENCIES
  gradle/libs.versions.toml
  system-tests/end2end-test/connector-runtime/build.gradle.kts
Labels: build

#248 chore: adds missing namespace in catalog query scope
  DEPENDENCIES
  extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiExtension.java
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiExtensionTest.java
Labels: enhancement

#252 fix: avoid exception DSP Request Action
  DEPENDENCIES
  core/federated-catalog-core/build.gradle.kts
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/DspCatalogRequestAction.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/query/DspCatalogRequestActionTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/PagingCatalogFetcherTest.java
  core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
Labels: bug

#253 fix: compile error after recent EDC updates
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/instrumentation/MockInjectionExtension.java
Labels: bug
