Repository eclipse-edc/FederatedCatalog, pull requests merged in 2025-04, with the labels that each got.

#305 feat: implement shutdown mechanism for `ExecutionPlan`
  core/crawler-core/src/main/java/org/eclipse/edc/catalog/cache/ExecutionManager.java
  core/crawler-core/src/test/java/org/eclipse/edc/catalog/cache/ExecutionManagerTest.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogDefaultServicesExtension.java
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/crawler/RecurringExecutionPlan.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtensionTest.java
  core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/crawler/RecurringExecutionPlanTest.java
  spi/crawler-spi/src/main/java/org/eclipse/edc/crawler/spi/model/ExecutionPlan.java
Labels: enhancement

#310 ci: replace inactive issues check with stale bot
  .github/workflows/close-inactive-issues.yml
  .github/workflows/stale-bot.yml
Labels: build

#311 build: fix compilation
  core/crawler-core/build.gradle.kts
  core/federated-catalog-core/build.gradle.kts
  core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
  dist/bom/federatedcatalog-base-bom/build.gradle.kts
  extensions/api/federated-catalog-api/build.gradle.kts
  extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
  gradle/libs.versions.toml
  system-tests/bom-tests/src/test/java/org/eclipse/edc/test/bom/BomSmokeTests.java
  system-tests/component-tests/build.gradle.kts
  system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
  system-tests/end2end-test/connector-runtime/build.gradle.kts
  system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
Labels: build

#312 refactor: reduce logs
  .github/workflows/verify.yaml
  core/crawler-core/src/main/java/org/eclipse/edc/catalog/cache/ExecutionManager.java
Labels: refactoring
